name: Build iOS (IPA)

on:
  workflow_dispatch: # Permite correrlo manualmente desde GitHub usando un botón

jobs:
  build_unity:
    name: 1. Compilar Unity (Export a Xcode)
    runs-on: ubuntu-latest
    steps:
      - name: Descargar Repositorio
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Ejecutar motor de Unity
        uses: game-ci/unity-builder@v4
        env:
          # Para que las computadoras de Unity en GitHub tengan permiso, deben iniciar sesión en tu cuenta
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: iOS
          allowDirtyBuild: true

      - name: Subir proyecto temporal de Xcode
        uses: actions/upload-artifact@v4
        with:
          name: XcodeProject
          path: build/iOS

  build_ipa:
    name: 2. Convertir Xcode a .IPA (Mac)
    needs: build_unity
    runs-on: macos-latest
    steps:
      - name: Descargar proyecto de Xcode
        uses: actions/download-artifact@v4
        with:
          name: XcodeProject
          path: build/iOS

      - name: Compilar IPA
        run: |
          cd build/iOS
          # Obligamos a la Mac virtual a compilar sin pedir firmas digitales de Apple
          xcodebuild clean build -project Unity-iPhone.xcodeproj -scheme Unity-iPhone -configuration Release -sdk iphoneos CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
          
          # Empaquetamos en formato IPA
          mkdir Payload
          # El nombre del .app puede variar según el proyecto, aseguramos copiar el generado
          mv build/Release-iphoneos/*.app Payload/
          zip -r SommelierAR.ipa Payload

      - name: Entregar archivo IPA final
        uses: actions/upload-artifact@v4
        with:
          name: SommelierAR_Aplicacion
          path: build/iOS/SommelierAR.ipa
